allow_all: false

topics:
  - /tf_static
  - /camera/camera/color/image_raw/compressed
  - /camera/camera/depth/image_rect_raw/compressedDepth

exclude_topics:
  - ^/rosout.*$

output_dir: ~/Workspace/Outputs/rosbags/test

storage: sqlite3           # sqlite3 or mcap (mcap requires its plugin installed)
compression: none          # none or zstd
compression_mode: file     # file or message (only used when compression != none)

max_bag_size: 0            # Bytes; >0 enables automatic file splitting by size (eg.600 every 10 minutes)
max_bag_duration: 0        # Seconds; >0 enables automatic file splitting by time (eg.1073741824 every 1 GiB)

qos_profile_overrides_path: ""
